### ISSUE TITLE
Illegal value for `line` error

### ISSUE THREAD

**Issue by djibe** [1000ch/vscode-csso#2]
Hi,
I try to process the following compressed CSS code 
`.card{box-shadow:none;border:1px solid grey}.foo{color:red}.bar{color:rgba(255,0,0,1)}`

VSCode sends me the error : Illegal value for `line` error.

However if I send some Code Beautifer again, and then apply CSSO, it finally works and outputs
`.card{box-shadow:none;border:1px solid gray}.bar,.foo{color:red}`

Any idea ?
Thanks for help

**Comment by 1000ch** [comment]
@djibe Can you still reproduce this problem?

**Comment by djibe** [comment]
Hi,
I totally forgot this Issue.
However I just tested again and got the same problem.

If I `format document` then run again, then it works.

**Comment by 1000ch** [comment]
@djibe
I feel like the issue doesn't happen in the latest version, please check it.

**Comment by djibe** [comment]
I cannot now. I'll try one day. Thx

**Comment by flanter21** [comment]
I'm still running into this problem.
